apiVersion: v1
kind: ServiceAccount
metadata:
  name: clearinghouse-app
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::641332413762:role/interview/gringotts-clearinghouse-dev-app-sa-role

